<a href="https://colab.research.google.com/github/JayMoya/My-Github-folder/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

A = np.array([[-5, 0], [4, 1]])
L = np.array([[6, -3], [2, 3]])

J = A + B      #  Sum
E= A - B      #  Diff 1
Y = B - A      #  Diff 2

print(A)
print(L)

print("-----------------------------")
print(J)
print("-----------------------------")
print(E)
print("-----------------------------")
print(Y)
print("-----------------------------")

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
-----------------------------
[[ 1 -3]
 [ 6  4]]
-----------------------------
[[-11   3]
 [  2  -2]]
-----------------------------
[[11 -3]
 [-2  2]]
-----------------------------
